/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#9a4600",
        "primary-container": "#e87524",
        "on-primary": "#ffffff",
        "on-primary-container": "#4f2000",
        "primary-fixed": "#ffdbc9",
        "primary-fixed-dim": "#ffb68d",
        "on-primary-fixed": "#321200",
        "on-primary-fixed-variant": "#763300",
        "secondary": "#984543",
        "secondary-container": "#fe9693",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#782c2c",
        "secondary-fixed": "#ffdad8",
        "secondary-fixed-dim": "#ffb3b0",
        "on-secondary-fixed": "#3f0207",
        "on-secondary-fixed-variant": "#7a2e2e",
        "tertiary": "#5e5e5b",
        "tertiary-container": "#969591",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#2d2e2b",
        "tertiary-fixed": "#e4e2de",
        "tertiary-fixed-dim": "#c8c6c2",
        "on-tertiary-fixed": "#1b1c19",
        "on-tertiary-fixed-variant": "#474744",
        "surface": "#fff8f4",
        "surface-dim": "#e1d8d2",
        "surface-bright": "#fff8f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fbf2eb",
        "surface-container": "#f5ece6",
        "surface-container-high": "#efe7e0",
        "surface-container-highest": "#eae1da",
        "surface-variant": "#eae1da",
        "surface-tint": "#9a4600",
        "on-surface": "#1f1b17",
        "on-surface-variant": "#574237",
        "inverse-surface": "#34302b",
        "inverse-on-surface": "#f8efe8",
        "inverse-primary": "#ffb68d",
        "background": "#fff8f4",
        "on-background": "#1f1b17",
        "outline": "#8a7265",
        "outline-variant": "#dec1b2",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "sm": "0.25rem",
        "md": "0.5rem",
        "lg": "0.75rem",
        "xl": "1rem",
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
      spacing: {
        "margin": "2rem",
        "margin-mobile": "1rem",
        "gutter": "1.5rem",
        "gutter-sm": "1rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
      },
      fontFamily: {
        "display-hero": ["Plus Jakarta Sans", "sans-serif"],
        "display-hero-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caption": ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero": ["52px", { lineHeight: "60px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "display-hero-mobile": ["34px", { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "600" }],
        "label-caption": ["11px", { lineHeight: "14px", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};
